

services:
  fastapi-app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:5
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  bot:
    build:
        context: .
        dockerfile: bot/Dockerfile
    container_name: tg_bot
    environment:
      - TOKEN=${TOKEN}
    depends_on:
      - fastapi-app

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - fastapi-app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data: